version: 2

project_name: reset-fiber-home

changelog:
  use: github
  sort: asc
  groups:
    - title: Novidades
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: Correções
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: Outros
      order: 999
  filters:
    exclude:
      - "^docs:"
      - "^chore:"
      - "^ci:"
      - Merge pull request
      - Merge branch
