version: 2

project_name: reset-fiber-home

before:
  hooks:
    - go mod tidy

builds:
  - id: reset-fiber-home
    main: .
    binary: reset-fiber-home
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    flags:
      - -buildvcs=false
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64

archives:
  - id: default
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - README.md

checksum:
  name_template: checksums.txt
  algorithm: sha256

changelog:
  use: github
  sort: asc
  groups:
    - title: Novidades
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: Correções
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: Outros
      order: 999
  filters:
    exclude:
      - "^docs:"
      - "^chore:"
      - "^ci:"
      - Merge pull request
      - Merge branch

release:
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"
